Update tweak_bib.csv
yihui/knitr pull request #1936
Opened 2020-12-21 21:09 UTC by beanumber

added `sessioninfo` tweak for R Core Team

2020-12-21 21:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/yihui/knitr?pullRequest=1936) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/yihui/knitr?pullRequest=1936) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/yihui/knitr?pullRequest=1936) it.</sub>

2020-12-21 22:43 UTC, yihui requested changes
Thanks! I'd rather do it this way (`Temple Lang` has exactly the same problem):
https://github.com/yihui/knitr/blob/f8f90baad99d873202b8dc8042eab7a88fac232f/R/citation.R#L99
so we don't have to deal with `{R Core Team}` on a package by package basis.

2020-12-22 03:33 UTC, beanumber commented
That makes sense. I'll close this.

2020-12-22 03:33 UTC, closed without merging

2020-12-22 04:36 UTC, yihui commented
Please feel free to submit another PR. Thanks!