Add 'rows affected' output when using sql engine
yihui/knitr pull request #2051
Opened 2021-09-25 22:21 UTC by edalfon

Adds a default output for `sql` chunks where `is_sql_update_query` evaluates to TRUE, as proposed in #2050.

It does it simply by:
- [Commit 1](https://github.com/edalfon/knitr/commit/f78e1c60ee00920aa48d03a3d166f2b6e3947435): propagating `DBI::DBI::dbExecute`'s result to `data`, so that users can set `output.var` and get the number of affected rows assigned to a variable.
- [Commit 2](https://github.com/edalfon/knitr/commit/d1f8cbf5255473b3ff4f711abb54ce2a4d036b82): adding a default output, indicating the number of rows affected.

I included a line in `NEWS.md` describing this. However, I did not include a test. I was not familiar with `knitr`'s testing procedures, but I learned from this recent PR (#1987) that there is one major test for `knitr`'s sql engine in another repository (https://raw.githubusercontent.com/yihui/knitr-examples/master/115-engine-sql.Rmd). This already covers the changes in this PR. I used it to test the changes and everything works. So I didn't really think it was necessary to include additional tests.

A final note: as discussed in [knitr's issue #1637](https://github.com/yihui/knitr/issues/1637), I think a similar change would be needed on RStudio's side, to make it also work when running chunks interactively (RStudio's Run current chunk, Run all, etc.). I haven't looked into that, though, and I have no idea who to poke for this, but I'd be happy to take a look.

Huge thanks for `knitr` and hope this helps a tiny bit.

2021-09-25 22:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/yihui/knitr?pullRequest=2051) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/yihui/knitr?pullRequest=2051) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/yihui/knitr?pullRequest=2051) it.</sub>

2021-09-27 10:07 UTC, cderv requested changes
I had a quick look. This looks fine overall but my main concern is about **knitr** writing text output. It is not the same to write a resulting table than writing text including a data result. I believe we must not presuppose what a user would like to have written as body text in its output document. Also, it seems the output text is not really relevant. Let's look into that. 

First, I am all for saving `data` for the result of `dbExecute()` so that it can be saved in `output_var` and then used later. 

Regarding printing, I think it would be ok to have like a informative `message()` printed, written in english and formatted as we want, but that would output like code result by default. **knitr** already give such messages in several places. However, it is not the same to return as body text (using `results = 'asis'`), all the more a formatted text in English with no way to customize. See my inline comments for why.

If we want to stay with the idea of outputting body text (`results = 'asis')`, we could offer configuration so that it can be customized. This is done already for the table when no `sql.print` function is provided. `options$tab.cap` can be specified to customize the table caption. Otherwise a default caption is shown.
See line 611 in the engine.R file for the SQL engine.
However, a table caption is not the same a text in a report. Personally, I would prefer we output a log-like message, like a message.

If we think customization, a user could save the result in `output_var`, and format itself the text he would like to show, as he would do with any other chunk output I believe, using the variable created and inline r chunks. So is this important to print a formatted output asis ? 

Also, regarding the textual output, I am thinking about your comment 
> it seems SQLite does not actually return the number of rows affected (apparently always returns 0). Yet, this is pretty standard in most RDBMS and it is also the default in DBI::dbExecute, so I guess this is just a quirk specific to SQLite.

If we are not sure that all RDBMS outputs a number of rows, I guess it would be puzzling to have written in your report 
```
Number of affected rows: 0
```
after a update query... 🤔 

From your RStudio projects (https://rstudio.cloud/project/2931829) (thanks for this by the way, that is awesome!), it seems that not all requests are returning a number of rows. For example,
```sql
DROP TABLE IF EXISTS toy;
```
after having created and computed on `toy` also returns 0 which writes in the output as Markdown text that 0 zeros are affected. It could be puzzling to users.

![image](https://user-images.githubusercontent.com/6791940/134886833-0e437fd2-c191-4d07-8042-4718bf3c2e65.png)

I have published your HTML document into R Pubs to easily see it: https://rpubs.com/cderv/knitr-pr-2051

So overall, about the SQL engine, my thinking is : 

* We should stay clause to what the DB specialized tools are doing. 
* `DBI::DBexecute()` returns a value, and it seems fair that we allow it to be accessible to the user
* `DBI::DBexecute()` does not print log message, and just return value. So we would in **knitr** do more than the tools offers. However, it makes sense to a publishing to tool to format some output (like we do with tables). But we must do this properly without assuming too much on what a user would like. 

After this long review, does anyone of you two @edalfon or @yihui are sharing my concerns ?

2021-09-27 14:00 UTC, edalfon commented on R/engine.R
> +    output = paste0("Number of affected rows: ", formatC(data, format = "fg", big.mark = ','))
Many thanks for reviewing this. I agree with pretty much everything you said. In particular, that saving `data` for the result of `dbExecute()` is key. And although I share your concerns on printing, perhaps I just feel less strongly about them.

And the reason I feel less strongly about those concerns is that I think the most common use cases for this output are:
- to get quick feedback while interactively trying out queries
- to leave documented the result of data processing on the DB side

But I did not think such an output would be mainly used in -let's say- a public facing document (e.g. final report or the like). In that case, as you said, the users can set `output.var` and format and use it as they wish. 

But for the two use cases above, I thought a quick default without configuring anything else would be useful (the user simply keep using a `{sql}` chunk and there you go). Therefore, I put a quick-and-dirty approach in that second commit. 

I totally share your concerns. It's not cool forcing `results = 'asis'`, hard-coding output in English and a particular number format. Ideally, the user should be able to customize all that. But I was not sure it was worth doing it. After all, if the users do want a particular format for that info, they can do it via `output.var`.  So, I guess one should weigh the benefits of doing that vs. the costs in terms of code complexity, maintainability, and so on. Perhaps I perceived that the costs outweigh the benefits. But you are for sure in a better position to make such assessment.

2021-09-27 14:01 UTC, edalfon commented
Many thanks for reviewing this. I agree with pretty much everything you said. In particular, that saving `data` for the result of `dbExecute()` is key. And although I share your concerns on printing, perhaps I just feel less strongly about them.

And the reason I feel less strongly about those concerns is that I think the most common use cases for this output are:
- to get quick feedback while interactively trying out queries
- to leave documented the result of data processing on the DB side

But I did not think such an output would be mainly used in -let's say- a public facing document (e.g. final report or the like). In that case, as you said, the users can set `output.var` and format and use it as they wish. 

But for the two use cases above, I thought a quick default without configuring anything else would be useful (the user simply keep using a `{sql}` chunk and there you go). Therefore, I put a quick-and-dirty approach in that second commit. 

I totally share your concerns. It's not cool forcing `results = 'asis'`, hard-coding output in English and a particular number format. Ideally, the user should be able to customize all that. But I was not sure it was worth doing it. After all, if the users do want a particular format for that info, they can do it via `output.var`.  So, I guess one should weigh the benefits of doing that vs. the costs in terms of code complexity, maintainability, and so on. Perhaps I perceived that the costs outweigh the benefits. But you are for sure in a better position to make such assessment.

2021-09-27 14:07 UTC, edalfon commented on R/engine.R
> +    output = paste0("Number of affected rows: ", formatC(data, format = "fg", big.mark = ','))
Agree!

What I did was trying to keep it similar to how the caption is formatted (line 614 on the same file)

```
rows_formatted = formatC(rows, format = "d", big.mark = ',')
```

but you are right that in that case, the user has options to configure the output

2026-09-16 22:08 UTC, yihui commented
Rebased onto current `master` and squashed into a single clean commit. This now builds on top of the `sql.is_statement` work merged in #1896: for statements (no result set), `DBI::dbExecute()`'s return value (affected rows) is propagated to the chunk `data` — so it can be assigned via `output.var` — and shown as the default output (`Number of affected rows: N`) otherwise.

Regarding the earlier design discussion (hard-coded English text and forced `results = 'asis'`): the default output is deliberately minimal, and users who want a custom format can assign the count via `output.var` and render it themselves. If you'd prefer the default text be customizable via an option, that can be layered on later.

Thanks @edalfon for the original PR.

2026-09-16 22:16 UTC, yihui commented
I've reworked this to address @cderv's 2021 review (CHANGES_REQUESTED), which had been left open. Rebased onto current `master` on top of the `sql.is_statement` work from #1896, as a single commit.

Point by point:

1. **Forcing `results = 'asis'`** — no longer done. The count is now emitted as normal (code-like) output, so it renders like any other chunk output and is not injected into the document body as prose. Users keep control via the usual output mechanisms.
2. **Hard-coded English sentence** — the text is now a template in a new chunk option `sql.statement.msg` (default `"Number of affected rows: {n}"`, where `{n}` is replaced by the count). Non-English reports can set their own template.
3. **`big.mark = ','`** — dropped, to avoid locale assumptions (comma grouping isn't universal).
4. **Puzzling `0` rows** (e.g. `DROP TABLE`, SQLite) — set `sql.statement.msg = NA` to suppress the output entirely.
5. **Style** — the new branch is chained as an `else if` on the existing output `if`, as suggested inline.

The uncontroversial part everyone agreed on (propagating `dbExecute()`'s return value so it can be captured via `output.var`) is retained. Verified all paths (default template, custom template, `NA` suppression, `output.var`, and that `SELECT` is unaffected) with a mocked DBI connection.

Thanks @edalfon for the original PR and @cderv for the detailed review.

2026-09-16 22:24 UTC, yihui approved these changes

2026-09-16 22:34 UTC, yihui commented
Updated: the affected-rows output is now **opt-in** rather than opt-out.

The knitr-examples CI job was failing because showing the affected-rows count by default changed the output of every existing statement chunk. To avoid altering current documents, the count is now only rendered when the user explicitly sets `sql.statement.msg` to a template string (e.g. `sql.statement.msg = "Number of affected rows: {n}"`, where `{n}` is the number). When the option is unset (the default), no extra output is produced.

The number of affected rows is still always available via `output.var` regardless of `sql.statement.msg`. This keeps the uncontroversial part (capturing the count) on by default, while making the textual output an explicit choice.

2026-09-16 22:58 UTC, merged