Add a generic engine for executing a command
yihui/knitr pull request #2073
Opened 2021-11-15 23:11 UTC by yihui

Close #1829 related: #1823 #1833

A few simple examples:

````
```{exec, command='Rscript'}
1 + 1
.libPaths()
```

```{exec, command='Rscript', args1='--vanilla'}
1 + 1
.libPaths()
```

```{exec, command='python'}
print(1 + 1)
```
````

2021-11-16 11:31 UTC, cderv approved these changes
It looks good to me. This is a simple enough implementation. We may find some edge case with `system2()` output at some point as usual. Known one is the encoding issue where `system2()` with `stdout = TRUE` has the same drawback as `system()` in this issue https://github.com/rstudio/rmarkdown/issues/2195#issuecomment-888148262

Also to clarify, is this mainly for internal use to simplify new engine documentation or do you plan to document this for user to use directly instead of implementing new engine ? 

We now need to see if the two custom engines in opened PR can be correctly implemented with this. But I believe so.

2021-11-16 11:31 UTC, cderv commented on R/engine.R
> +    f2 = wd_tempfile(cmd2)  # capture stderr
It seems like `f2` will be created in all case. I have those tempfile left after running the example. 
This happens at least on Windows. `file.size(f2)` is 0 though, so it creates no error. 

I think we need to unlink on exit

```suggestion
    f2 = wd_tempfile(cmd2)  # capture stderr
    on.exit(unlink(f2), add = TRUE)
```

2021-11-16 17:21 UTC, yihui reviewed
> We may find some edge case with `system2()` output at some point as usual. Known one is the encoding issue where `system2()` with `stdout = TRUE` has the same drawback as `system()` in this issue [rstudio/rmarkdown#2195 (comment)](https://github.com/rstudio/rmarkdown/issues/2195#issuecomment-888148262)

Good point. I recently ran into this issue, too: https://github.com/rstudio/blogdown/commit/e4a3f38548f489f48a6706d4c7296b70cf024af6 I think this problem should easy to fix (by testing if the output is UTF-8 or not via `xfun:::invalid_utf8()`; if it is UTF-8, we mark it explicitly with `Encoding() <- 'UTF-8'`). That said, this problem is solvable only for commands that write out text in UTF-8 (I think both Pandoc and Hugo do, but this is not true for all commands, such as `Rscript`).

> Also to clarify, is this mainly for internal use to simplify new engine documentation or do you plan to document this for user to use directly instead of implementing new engine ?

This will be a user-facing engine and will be publicly documented. Both us and users could create new command engines based on this one.

2021-11-16 17:57 UTC, cderv commented on R/engine.R
> +  opts = options$engine.opts %n% options[c('command', 'file', 'ext', 'args', 'args1', 'args2')]
I think we should try to do that when an argument is used often. Like `file` with the `cat()` engine. For other args,we could still provide them in `engine.opts` - I don't think this is that confusing, and I think it is worth it. 

> Then we need to document the file option differently for the two engines, which is probably not a big problem.

I feel at some point we may need to make a documentation of chunk option per-engine. I don't think it is a problem to have a chunk option meaning different things for different engine. We already have differences for some chunk options I think. 

But if we can avoid, I agree this is better.

2021-11-16 18:50 UTC, yihui commented on R/engine.R
> +  opts = options$engine.opts %n% options[c('command', 'file', 'ext', 'args', 'args1', 'args2')]
> I think we should try to do that when an argument is used often.

That sounds like a good idea.

> I feel at some point we may need to make a documentation of chunk option per-engine.

I agree.

2021-11-17 11:51 UTC, cderv requested changes
I spend time tested this more on Windows by doing https://github.com/yihui/knitr-examples/pull/84

Found issue with some edge case. 

Also, not 100% convinced on how all the options are supposed to work. I guess few user should change the default, but I feel it may be better to be stricter on checks to help future users (and us)

2021-11-17 11:51 UTC, cderv commented on R/engine.R
> +      res
It seems like this won't work as expected. 

I tried to test with 

````markdown
```{exec, command = 'Rscript', error = TRUE}
1 + ""
```
````

but running 
```r
res = system2(cmd, shQuote(a), stdout = TRUE, stderr = f2, env = options$engine.env)
```
will result in 
```r
> res
character(0)
attr(,"status")
[1] 1
```

Error is correctly written to `f2` and no error is catched. a warning instead 
````
Warning message:
In system2(cmd, shQuote(a), stdout = TRUE, stderr = f2, env = options$engine.env) :
  running command '"Rscript" "Rscript44087452f49.Rscript"' had status 1
````
because (from help page of `system2`)
> If the command could not be run an R error is generated. If command runs but gives a non-zero exit status this will be reported with a warning and in the attribute "status" of the result: an attribute "errmsg" may also be available.

Shouldn't we output the error if `error = TRUE` something like 

```suggestion
    tryCatch({
      res = system2(cmd, shQuote(a), stdout = TRUE, stderr = f2, env = options$engine.env)
      # check error in the content run
      if (!is.null(attr(out, 'status')) && file.exists(f2) && file.size(f2) > 0) {
         e <- readLines(f2)
         if (!options$error) stop(paste(e, collapse = '\n')) else e # f2 may not be UTF-8
      } else {
        res
      }
    }, error = function(e) {
        # Error in the command run
        if (!options$error) stop(e)
        paste('Error in running command', cmd)
      }
    )
```

We don't get anything as output even with `python
````
```{exec, command = 'python', error = TRUE, eval = TRUE}
print(1 + "")
```
````

2021-11-17 11:51 UTC, cderv commented on R/engine.R
> +      res = system2(cmd, shQuote(a), stdout = TRUE, stderr = f2, env = options$engine.env)
Note: `stderr` is correctly written into a file but we get the Encoding issue. </summary>

````
Erreur dans 1 + "" : argument non num?rique pour un op?rateur binaire
Ex?cution arr?t?e
````
As a thought, I believe this is something that will always be there unless we use correct tooling to handle this. Using `file_string()` or `read_utf8()` will assume file is UTF-8. This won't be the case here. 
And possibly, `system2` is broken for that as it writes the file in the wrong Encoding on my Windows. 🤔 
(file is indicated as UTF-8 when I open in an editor but content is latin-1)

This means that 
```
stop(file_string(f2))
```
will error. 

So when `error = FALSE`, the default, we get something like 
````
running: Rscript Rscript440849036e7d.Rscript
Quitting from lines 10-11 (124-exec-engine.Rmd) 
Error in doTryCatch(return(expr), name, parentenv, handler) : 
  Erreur dans 1 + "" : argument non num<e9>rique pour un op<e9>rateur binaire
Ex<e9>cution arr<ea>t<e9>e
In addition: Warning messages:
1: In system2(cmd, shQuote(a), stdout = TRUE, stderr = f2, env = options$engine.env) :
  running command '"Rscript" "Rscript440849036e7d.Rscript"' had status 1
2: In read_utf8(file) :
  The file Rscript44087dc0251c is not encoded in UTF-8. These lines contain invalid UTF-8 characters: 1, 2
````

Maybe this is a edge case. 

Checked with python and I get this with `error = FALSE`
````
running: python python4408320b5d3a.python
Quitting from lines 10-11 (124-exec-engine.Rmd) 
Error in doTryCatch(return(expr), name, parentenv, handler) : 
  Traceback (most recent call last):
  File "C:\Users\chris\Documents\DEV_R\knitr-examples\python4408320b5d3a.python", line 1, in <module>
    print(1 + "")
TypeError: unsupported operand type(s) for +: 'int' and 'str'
In addition: Warning message:
In system2(cmd, shQuote(a), stdout = TRUE, stderr = f2, env = options$engine.env) :
  running command '"python" "python4408320b5d3a.python"' had status 1
````

So it could be an error depending on the command use. That will be tricky - unless only R as this weird non UTF-8 stuff. This could not be a problem anymore with new R UTF-8

2021-11-17 17:40 UTC, yihui commented on R/engine.R
> +  a = c(opts$args1, if (is.function(opts$args)) opts$args(options$code, f), opts$args2)
Yes, we should allow these options to take character values.

Checking the value types of these options is also a good idea.

2021-11-17 19:19 UTC, cderv commented on R/engine.R
> +  } else if (is.character(opts$file) {
```suggestion
  } else if (is.character(opts$file)) {
```

Sorry missing parenthesis

2022-01-04 21:12 UTC, yihui commented on R/engine.R
> +      res = system2(cmd, shQuote(a), stdout = TRUE, stderr = f2, env = options$engine.env)
Right. I shouldn't assume UTF-8 here. I'll see what I can do.

2022-01-04 21:40 UTC, yihui commented on R/engine.R
> +      res = system2(cmd, shQuote(a), stdout = TRUE, stderr = f2, env = options$engine.env)
Never mind. I just saw you used `readLines()` in 084f9c34a9f553e4ee5570c302edaf0eb2baeb37, which is probably fine.

Yes, waiting for the UTF-8 version of R may be the best way to go :)

2022-01-07 17:02 UTC, cderv reviewed
I added a few comments based on what I have said in https://github.com/yihui/knitr-examples/pull/84#pullrequestreview-846785602

2022-01-10 23:32 UTC, yihui commented on R/engine.R
> +      file
Fixed now.

2022-01-10 23:35 UTC, yihui commented on R/engine.R
> +  # TODO: allow users to set the language name
Let me revisit this issue after this PR is merged. I think it was a bad idea to use `engine` as the language name here: https://github.com/yihui/knitr/blob/47e831ed437e314b7d1a89fcc60f75c4d70fa12e/R/hooks-md.R#L182-L185
We need to make it more easily configurable via a dedicated option. I don't like the idea of modifying `options$engine` only for the purpose of syntax highlighting.

2022-01-10 23:35 UTC, yihui commented on R/engine.R
> +}
I dealt with it in 957d74690e8a745f55bd129061ef8877d1fcb13c.

2022-01-11 09:35 UTC, cderv commented on R/engine.R
> +  # TODO: allow users to set the language name
> Let me revisit this issue after this PR is merged

I am find. Should we open an issue to track in **knitr** ? That would be helpful IMO but you may use other process to not forget 😅

2022-01-11 14:27 UTC, yihui commented on R/engine.R
> +  # TODO: allow users to set the language name
My "other process" is to simply search for "TODO" in the project :) I won't forget this one.

2022-01-11 14:29 UTC, yihui commented
Yes, we need to adapt other engines, and tell new contributors to use this new engine, e.g., https://github.com/yihui/knitr/pull/2092. I think this `exec` engine still has some room for improvement, and we will know more when we look at these PRs more closely. One thing on my mind right now is that this engine probably needs an `output` option, in case the command engine generates an important output file, such as a figure file.

2022-01-11 14:39 UTC, cderv commented
There is always room from improvement ! 😉 
I think we should merge this with current feature, open issues to track potential ideas we have (like the `output`) and see with other PR at usage if other stuff are missing.

2022-01-11 14:42 UTC, yihui commented
Yes, I'm looking at other PRs right now to get a better idea of the future improvement. I hope this PR should at least close the three PRs #1829 #1823 and #1833. #2092 is a little more complicated.

2022-01-13 05:02 UTC, merged