Provide an `embed` engine to embed external file verbatim
yihui/knitr pull request #2076
Opened 2021-11-30 15:38 UTC by yihui

close #1931, and also close #1275

2021-12-01 16:35 UTC, cderv requested changes
This looks ok. Only one drawback while testing in the way we are setting the default language. 
I let you have a look

2021-12-01 16:35 UTC, cderv commented on R/engine.R
> +  options$class.source = options$class.source %n% tolower(lang)
I was asking myself the question so putting this here for reference. Maybe we could add a comment to not forget

`eng_embed` uses `eng_verbatim` , order of options: 
1. `options$engine.opts$lang`
2. `options$lang`
3. `options$language`
4. `options$class.source`

So I would use one of the first because `class.source` can be used to add a class in addition to language. and language will be removed later in `eng_cat`. Currently it can cause issues likes this : 

````markdown
```{cat, engine.opts = list(file = "style.css"), echo = FALSE}
h1 {
  color: red;
}
```
# Specifying language

```{embed, lang = "md"}
"style.css"
```
````

will return 
````markdown
# Specifying language


```{.md .css}
h1 {
  color: red;
}
```
````

because we pass the file extension as a `class.source` without setting the other attributes used in `eng_verbatim`. 
What we want is to just change the default value for `eng_verbatim` (which is `default` string)

We could 

* Add a helper to check attributes and set default otherwise 
  ```
  set_lang_attr = function(options, default) {
    options$engine.opts$lang = options$engine.opts$lang %n%
        unlist(options[c('lang', 'language')])[1] %n%
        options$class.source %n% default
    options
  }
  ```
  to use in both `eng_embed` (`options = set_lang_attr(options, lang)` and `eng_verbatim` (`options = set_lang_attr(options, "default")`

* Add an internal `options$default.lang` in `eng_verbatim` than we can use in `eng_embed`
  ````diff
  diff --git a/R/engine.R b/R/engine.R
  index ce2e58af..110927cd 100644
  --- a/R/engine.R
  +++ b/R/engine.R
  @@ -787,7 +787,7 @@ eng_verbatim = function(options) {
    # or class.source; if all are empty, use 'default'
    options$engine.opts$lang = options$engine.opts$lang %n%
      unlist(options[c('lang', 'language')])[1] %n%
  -    options$class.source %n% 'default'
  +    options$class.source %n% options$default.lang %n% 'default'
  
    eng_cat(options)
  }
  @@ -805,7 +805,7 @@ eng_embed = function(options) {
    lang = sub('^R', '', lang)  # Rmd -> md, Rhtml -> html, etc.
    if (lang == 'nw') lang = 'tex'
  }
  -  options$class.source = options$class.source %n% tolower(lang)
  +  options$default.lang = tolower(lang)
  eng_verbatim(options)
  }

  ````

2021-12-01 16:58 UTC, cderv commented
Also something came to mind. 

What about : 
````mardkown
```{verbatim, file = "style.css"}
```
````

This would avoid a specific engine, but we would loose the hability to provide file as content of the code chunk - only through option. Basically, you can provide `file` to `verbatim` engine, and in that case, chunk content is ignored and replaced by the file content. Default language is set to file extension. 

Have you thought of that and already decided on a new `embed` engine instead ?

2021-12-02 05:36 UTC, yihui commented on R/engine.R
> +  options$class.source = options$class.source %n% tolower(lang)
I applied the helper function you provided. Thanks!

2021-12-02 05:40 UTC, yihui commented
> ```` ```{verbatim, file = "style.css"}````

This is supported now with https://github.com/yihui/knitr/commit/545aed32274955be2109150ce1ef4e24fe3732de. Note that the `file` option is not specific to the `verbatim` engine but any engine. This is a feature that I have wanted to add for long.

Now the only benefit of the `embed` engine is that you can specify the file path inside the code chunk, which makes the syntax a little terser.

2021-12-02 09:35 UTC, cderv requested changes
> This is supported now with [545aed3](https://github.com/yihui/knitr/commit/545aed32274955be2109150ce1ef4e24fe3732de). Note that the `file` option is not specific to the `verbatim` engine but any engine. This is a feature that I have wanted to add for long.

I was getting used to using `code = xfun::read_utf8("test.R")` 😄 But this will be easier for sure. That is a great addition ! 

> Now the only benefit of the `embed` engine is that you can specify the file path inside the code chunk, which makes the syntax a little terser.

The other benefit is that you have the the language set by default to the file extension. The `verbatim` engine won't do that right ? 

* `verbatim`
````
```{verbatim, file = "foo.R", lang = "r"}
```
````

* `embed`
````
```{embed, file="foo.R"}
```
````

That is a bit shorter. 

There is one small issues found by testing (I'll add to knitr-example afterwards), Otherwise looks good! 

Thanks!

2021-12-02 09:35 UTC, cderv commented on NEWS.md
> +
We should change with this new file option, shouldn't we ? 

`````suggestion
- Added a new engine named `embed` to embed external plain-text files. It is essentially a simple wrapper based on the `verbatim` engine, with the chunk content read from an external file and default language guessed from file extension. That is,

  ````
  ```{embed, file="foo.R"}
  ```
  ````
  
  is equivalent to
  
  ````
  ```{verbatim, file = "foo.R", lang = "r"}
  ```
  ````
  
 If you provide the chunk option `file` to the `embed` engine, it will read the file and show its content verbatim in the output document. Alternatively, you can specify the file path in the chunk body, e.g.,
  
  ````
  ```{embed}
  "foo.txt"
  ```
  ````
  
  The quotes are optional but can be helpful for editors (e.g., RStudio IDE) to autocomplete the file paths.
  
  The syntax highlighting language name is from the filename extension by default, and you can override it with the chunk option `lang` (e.g., `file = "foo.sh", lang = "bash"`) which is then identical to the `verbatim` engine.

`````

2021-12-02 09:35 UTC, cderv commented on R/engine.R
> +  if (is.null(options$file)) {
I think we need to assign the file option to `f` and just modify it if it is NULL
```suggestion
  if (is.null(f <- options$file)) {
```

Otherwise, this will error as f not define 
```
if (nchar(lang <- file_ext(f[1])) > 1) {
```

2021-12-03 19:54 UTC, yihui reviewed
Good suggestions. Thanks!

2021-12-03 20:05 UTC, merged

2021-12-06 14:51 UTC, cderv commented
I have added example for this in **knitr-example**

2021-12-06 14:58 UTC, yihui commented
Great. Thanks!