added options immedate & replace to eng_SQL
yihui/knitr pull request #2128
Opened 2022-05-18 09:10 UTC by AWKruijt

As discussed here: https://github.com/rstudio/rmarkdown/issues/2241

I haven't added test files as these changes require access to an sql server with permission to create temporay tables. Haven't found that in an open database. 

I'm excited about this! :)

2022-05-18 09:37 UTC, AWKruijt commented
reptable =  gsub('(^.*into[[:space:]]+)(#.+)([[:space:]]+from.*$)', '\\2', sql, ignore.case = T)
on line 618 fixes the error handling on attempts to replace non-temporary tables.

2022-05-18 09:38 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/yihui/knitr?pullRequest=2128) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/yihui/knitr?pullRequest=2128) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/yihui/knitr?pullRequest=2128) it.</sub>

2022-05-18 10:37 UTC, AWKruijt commented
Just checking (I'm really inexperiences >.<): I'm seeing this super inviting 'Update branch' button (with alternate update with rebase) - do I push that or do I just wait now? :)

2022-05-18 10:54 UTC, cderv commented
You can push that to update but that is not necessary. We'll do it ourself, or just merge the branch. Your change target in code part that has not been modified in some time, and tests are passing ok. So you can leave that way, and just wait for us to review. I added that in my TODO list. Thanks !

2022-05-18 14:44 UTC, yihui approved these changes
I don't really know much about SQL, so I only reviewed the coding style. BTW, the changes with pure white spaces in this PR need to be discarded (if you don't know how, we can handle this before we merge).

Thanks!

2022-05-20 09:57 UTC, AWKruijt commented on R/engine.R
> +    }
Thanks!  I'll try to get all of it solved in the coming days :)

2022-05-24 13:34 UTC, cderv requested changes
Thanks. 

I made a few comments to share a few thoughts. 
Currently, with this change : 

* We are passing `immediate` no matter what
* We are setting the default value to `FALSE`  whereas it seems to be NULL in **DBI** which has a different meaning.

I don't really know which backend that would impact or not, but I think it would be safer to prevent this somehow using more conditional logic. I can help tweak the PR if you do not know how to do it. 

Thanks

2022-05-24 13:34 UTC, cderv commented on R/engine.R
> +      DBI::dbExecute(conn, query, immediate = immediate)
I think we need to take precaution here. 
`DBI::dbExecute()` is a generic and `immediate` argument, is indeed among the specifications. However, `immediate` is not part of the generic argument to improve compatibility with the different backends. 
https://dbi.r-dbi.org/reference/dbexecute#additional-arguments-1

> The following arguments are not part of the dbExecute() generic (to improve compatibility across backends) but are part of the DBI specification:
> * params (default: NULL)
> * immediate (default: NULL)
> 
> They must be provided as named arguments. See the "Specification" sections for details on their usage

This is valid for other calls too.

2022-05-24 13:34 UTC, cderv commented on R/engine.R
> +  immediate=  F
**DBI** seems to default to NULL for `dbExecute` and `dbGetQuery`, which means 
https://dbi.r-dbi.org/reference/dbexecute#specification-for-the-immediate-argument-1
> The default NULL means that the backend should choose whatever API makes the most sense for the database

So setting FALSE, will change behavior for all the DB that backends that will use TRUE by default. 

Maybe we should stick to that, and pass `immediate = TRUE` or `FALSE` when the chunk option is explicitly set ?

2022-05-24 13:34 UTC, cderv commented on R/engine.R
> +  immediate=  F
**DBI** seems to default to NULL for `dbExecute` and `dbGetQuery`, which means 
https://dbi.r-dbi.org/reference/dbexecute#specification-for-the-immediate-argument-1
> The default NULL means that the backend should choose whatever API makes the most sense for the database

So setting FALSE, will change behavior for all the DB that backends that will use TRUE by default. 

Maybe we should stick to that, and pass `immediate = TRUE` or `FALSE` when the chunk option is explicitly set ?

2022-05-24 14:18 UTC, yihui commented on R/engine.R
> +        replace= T
Yes, let's use the `sql.` prefix for the new options here.

> I don't know if we can end up with a rule on under which condition which should use `engine.opts`, bare chunk option name or prefixed option name. I think we should try being consistent.

I agree. It has been a mess, which I don't like, but I feel it's tough to decide which is better:

````md
```{sql, engine.opts = list(immediate = TRUE, replace = TRUE)}
````

````md
```{sql, sql.immediate = TRUE, sql.replace = TRUE}
````

> chunk engine is enough to scope the variable (advanced usage of chunk options hooks would require checking the engine, and then checking the option in case of same option name used by two different engine with different meaning - may never happen though).

That's also what I think.

2022-06-14 10:45 UTC, AWKruijt commented
Sorry for the radio silence - things where happening. Thanks for all the input! I've implemented as much as I could - see commit [358d552](https://github.com/yihui/knitr/pull/2128/commits/358d55248dc07c6147b4276fea793bf6312cea65).

A big one that is open for debate still is whether/how to make it so that paramater immediate is NOT passed to dbGetQuery when the user did not set it. I suppose that's what we want, given that it's cleanest if we also don't pass the NULL value if sql.immediate is not actively invoked. For option params the code has a split based on length(params) == 0 and separately defined calls to DBI::dbGetQuery() with and without passing of params. We could expand that into four calls (with/without immediate and/or params), but perhaps something along the lines of a do.call with a list of arguments could be preferable? I did try every trick I could think of along the lines of DBI::dbGetQuery(conn, sql, if(exists('immedate'){immedate = immediate}) but no joy :/

2022-06-24 09:48 UTC, AWKruijt commented
Alas, I notice that in practice the replace option doesn't always work flawlessly due to the regex to lift the tempary table name from the query also picking up new lines (`/n`) immediately after the #table name. Fixed the regex and made another correction to the getQuery call with params where I had made it use `sql` instead of `query`.

2022-07-08 14:32 UTC, cderv reviewed
I am not sure I understand why we need the `exist()` for retrieving the option. I commented about that. 

> We could expand that into four calls (with/without immediate and/or params), but perhaps something along the lines of a do.call with a list of arguments could be preferable? I did try every trick I could think of along the lines of DBI::dbGetQuery(conn, sql, if(exists('immedate'){immedate = immediate}) but no joy :/

After looking closer to DBI, I think the most important thing is not changing the default. So that 
````
dbExecute(con, immediate = options$sql.immediate)
```` 
correctly pass NULL value. I don't think that methods that don't have `immediate` will break because of the `...` - it will just be unused argument in this. So we may be fine passing it anyway. 

Otherwise, the `do.call` alternative seems like a good one, with a list of argument containing `immediate` or not depending on the option. Did you try that already ? 

Also, did you come up with test document for this PR ? Just curious to avoid making a new one. 

Thanks

2026-09-16 22:33 UTC, yihui commented
Rebased onto current `master` (on top of the `sql.is_statement` work from #1896) and reworked to address @cderv's review (CHANGES_REQUESTED).

Key change per the review: **the DBI default for `immediate` (`NULL`) is preserved**. `immediate` is not part of the `dbExecute()`/`dbGetQuery()` generics, and `NULL` means "let the backend choose the most suitable API", so we must not force `FALSE`. The new chunk option `sql.immediate` is now passed to DBI (via `do.call()`, the approach you suggested) **only when it is explicitly set** to `TRUE`/`FALSE`; otherwise the argument is omitted entirely. This is the `do.call` alternative discussed in the thread, avoiding the `exists()` trick.

Also uses the `sql.` option prefix (`sql.immediate`) for consistency with `sql.print`/`sql.show_interpolated`, and fixes the `dbGetQuery(conn, sql, params=)` → `query` reference.

Scope note: I dropped the `sql.replace` / temporary-table feature from the original PR. Its table-name regex was acknowledged upthread to be fragile (newlines, `#temp` parsing) and it is SQL-Server-specific, which is hard to test in CI. This PR now focuses on `sql.immediate` alone; `replace` can be revisited in a separate PR if there's demand.

Thanks @AWKruijt for the original contribution and @cderv for the detailed review.

2026-09-17 01:02 UTC, yihui commented
This adds a general `sql.args` chunk option — a named list forwarded to the underlying DBI query functions (`dbExecute()`, `dbSendQuery()`, `dbGetQuery()`) — so any backend-specific argument can be passed, e.g. `sql.args = list(immediate = TRUE)`. Extra args are passed only when supplied, so DBI's own defaults are preserved otherwise. Added validation, a NEWS entry with an example, and verified dispatch via mocked DBI. Thanks @AWKruijt!

2026-09-17 01:04 UTC, yihui approved these changes

2026-09-17 01:04 UTC, yihui commented on R/engine.R
> +    stop2("The 'sql.args' chunk option must be a named list.")
```suggestion
```

2026-09-17 01:07 UTC, merged