Faster processing of dependencies
yihui/knitr pull request #2321
Opened 2024-01-31 14:00 UTC by knokknok

In reference to #2318, would the following work?

2024-03-30 13:58 UTC, atusy requested changes
@knokknok

Thank you for the PR.
It seems you are on the right direction.
I added some nit-picking comments about docs and formats.

2024-03-30 14:00 UTC, atusy commented on R/cache.R
> +#' @param chunk_label The chunk label of the current code chunk.
I would also describe the default behavior that `NULL` builds dependencies for the all the available chunks.

2024-04-01 20:43 UTC, yihui approved these changes
I've revised the PR according to @atusy's feedback. Thanks!

2024-04-01 20:45 UTC, merged

2024-04-02 00:13 UTC, atusy commented
My pleasure!
Looks perfect!!